---

- name: Install and configure decktape PDF printing dependency
  include: install_decktape.yml

- name: Add line to /etc/hosts file mapping local ip to specified domain
  lineinfile: 
    line: "{{ ansible_eth0.ipv4.address }} {{ domain }}"
    dest: /etc/hosts
    state: present

- name: Clone GitPitch repo
  git:
    repo: "{{ gitpitch_repo }}"
    dest: "{{ gitpitch_dir }}"
    accept_hostkey: yes
    key_file: "{{ git_key_file|default(omit) }}"
    version: "{{ git_branch }}"
  tags: git

- name: Run sbt on dist
  shell: "sbt dist"
  args:
    chdir: "{{ gitpitch_dir }}"
  tags: sbt
  
- name: Copy in production config file
  template:
    src: production.conf.j2
    dest: "{{ gitpitch_dir }}/conf/production.conf"
  tags: conf

- name: Create gitpitch ssl directory
  file:
    path: "{{ gitpitch_dir }}/ssl"
    state: directory

- name: Copy in custom SSL cert bundle from secrets directory
  copy:
    src: "secrets/{{ cert_bundle }}"
    dest: "{{ gitpitch_dir }}/ssl/{{ cert_bundle }}"
  when: "cert_bundle is defined and cert_bundle"

- name: Unzip target deployment
  unarchive:
    src: "{{ gitpitch_target_dir }}/{{ gitpitch_target }}.zip"
    dest: "{{ gitpitch_target_dir }}"
    remote_src: Trueh