---

- name: restart application
  supervisorctl: name={{ application_name }} state=restarted

- name: restart supervisord
  service: name=supervisor state={{ item }}
  with_items:
    - stopped
    - started
  tags:
    - supervisor